### ISSUE TITLE
no function clause matching in Arc.Ecto.Type.dump/2

### ISSUE THREAD

**Issue by MatthewRDodds** [stavro/arc_ecto#44]
**Context:**
This is what my `attachment` looks like:

```
%MyApp.Attachment{__meta__: #Ecto.Schema.Metadata<:built, "attachments">,
 file: %Plug.Upload{content_type: "image/png",
  filename: "Screen Shot 2016-09-07 at 3.28.23 PM.png",
  path: "/var/folders/6v/wlbdtzc11z52b2q5lxttmg4m0000gn/T//plug-1473/multipart-285821-783023-1"},
 id: nil, inserted_at: nil,
 submission: #Ecto.Association.NotLoaded<association :submission is not loaded>,
 submission_id: 16, updated_at: nil}
```

But when I try to do `MyApp.Repo.insert attachment` I get the following exception

**Stacktrace:**
```
** (FunctionClauseError) no function clause matching in Arc.Ecto.Type.dump/2
        (arc_ecto) lib/arc_ecto/type.ex:39: Arc.Ecto.Type.dump(MyApp.File, %Plug.Upload{content_type: "image/png", filename: "Screen Shot 2016-09-07 at 3.28.23 PM.png", path: "/var/folders/6v/wlbdtzc11z52b2q5lxttmg4m0000gn/T//plug-1473/multipart-285267-670891-1"})
        (ecto) lib/ecto/type.ex:629: Ecto.Type.do_adapter_dump/3
        (ecto) lib/ecto/repo/schema.ex:606: Ecto.Repo.Schema.dump_field!/6
        (ecto) lib/ecto/repo/schema.ex:619: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
        (stdlib) lists.erl:1262: :lists.foldl/3
        (ecto) lib/ecto/repo/schema.ex:617: Ecto.Repo.Schema.dump_fields!/5
        (ecto) lib/ecto/repo/schema.ex:566: Ecto.Repo.Schema.dump_changes!/6
        (ecto) lib/ecto/repo/schema.ex:182: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
        (ecto) lib/ecto/repo/schema.ex:595: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
        (ecto) lib/ecto/adapters/sql.ex:472: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:973: DBConnection.transaction_run/4
        (db_connection) lib/db_connection.ex:897: DBConnection.run_begin/3
```

This is my attachment model:

```elixir
defmodule MyApp.Attachment do
  use MyApp.Web, :model
  use Arc.Ecto.Schema

  schema "attachments" do
    field :file, MyApp.File.Type
    belongs_to :submission, MyApp.Submission

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [])
    |> cast_attachments(params, [:file])
    |> validate_required([:file])
  end
end
```

File is just:

```elixir
defmodule MyApp.File do
  use Arc.Definition
  use Arc.Ecto.Definition

  @versions [:original]
end
```

Is it something I'm missing? I looked at the line [referenced in the stacktrace](https://github.com/stavro/arc_ecto/blob/master/lib/arc_ecto/type.ex#L39) but it seemed like a red herring. Forgive me if I'm missing something obvious, new to elixir.

**Comment by MatthewRDodds** [comment]
A simpler reproduction is:

```elixir
Bugshift.Repo.insert %Bugshift.Attachment{file: %Plug.Upload{content_type: "image/png", filename: "Screen Shot 2016-09-07 at 3.28.23 PM.png", path: "/var/folders/6v/wlbdtzc11z52b2q5lxttmg4m0000gn/T//plug-1473/multipart-285821-783023-1"}}
eee

That gives me the same backtrace as above.

**Comment by stavro** [comment]
The "simpler reproduction" is missing the necessary call to `cast_attachments` - the `%Plug.Upload{}` should not be set to the attribute field directly.

In the first example, can you show me how you are calling `MyApp.Attachment.changeset`?

**Comment by MatthewRDodds** [comment]
Ah, that's my issue, before I was using `Ecto.build_assoc` which must not run through the changeset either, but when I use a changeset in the simple example I no longer see the error. Thanks!

**Comment by stavro** [comment]
:+1: Good to hear!
