### ISSUE TITLE
Error uploading to S3 with 0.10.0

### ISSUE THREAD

**Issue by MvanDiemen** [stavro/arc_ecto#95]
Hi guys,

I've just upgraded from 0.8.0 to 0.10.0 and I get an error. On 0.8.0 everything works fine but on 0.10.0 it does not, I think it can be related to [Elixir #7671](https://github.com/elixir-lang/elixir/issues/7671)
```
08:44:38.421 [error] Task #PID<0.1354.0> started from #PID<0.1347.0> terminating
** (FunctionClauseError) no function clause matching in :raw_file_io_raw.open_layer/3
    (kernel) raw_file_io_raw.erl:24: :raw_file_io_raw.open_layer("/tmp/ZCDINTBLEWU5P4DKGSCSFKABUMHMXJUT", [:read, {:read_ahead, 65536}, :binary, :binary], [:raw, :raw])
    (elixir) lib/file/stream.ex:78: anonymous fn/3 in Enumerable.File.Stream.reduce/3
    (elixir) lib/stream.ex:1362: anonymous fn/5 in Stream.resource/3
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4
    (elixir) lib/task/supervised.ex:306: Task.Supervised.stream_reduce/7
    (elixir) lib/enum.ex:2979: Enum.reverse/1
    (elixir) lib/enum.ex:2613: Enum.to_list/1
    (ex_aws_s3) lib/ex_aws/s3/upload.ex:89: ExAws.Operation.ExAws.S3.Upload.perform/2
Function: #Function<1.109072281/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```
I have downgraded to 0.8.0 and everything returns to normal again.

**Comment by MvanDiemen** [comment]
After a quick check, it also works fine with 0.9.0.

**Comment by MvanDiemen** [comment]
Very strange, after uploading with 0.8.0 and 0.9.0, this now suddenly works with 0.10.0 again.
